### ISSUE TITLE
Getting Unauthorized Errors

### ISSUE THREAD

**Issue by gonzalu** [longgui0318/comfyui-llm-assistant#1] opened 2024-04-30 18:59 UTC
Hello, just started getting errors ... it worked fine yesterday. I tried a new API Key but still fails: 

HTTP Request: POST https://openrouter.ai/api/v1/chat/completions "HTTP/1.1 401 Unauthorized"

Any idea what might be wrong? 

Thank you.

**Comment by longgui0318** [comment] 2024-04-30 20:11
I tested it and it behaves normally, which means there is no change in the server api side, maybe the problem is in the configuration, you can try to confirm the configuration if you are on openrouter. Please keep the following configuration

`api_base: "https://openrouter.ai/api/v1"`

Then make sure the api_key is right

You can detach this plugin and use a separate api call test.

**Comment by longgui0318** [comment] 2024-04-30 20:19
You can try running the code in python alone to test it. Note that changing the api_key in the.
```
from openai import OpenAI

# gets API Key from environment variable OPENAI_API_KEY
client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key="api_key",
)

completion = client.chat.completions.create(
  model="mistralai/mistral-7b-instruct:free",
  messages=[
    {
      "role": "user",
      "content": "Say this is a test",
    },
  ],
)
print(completion.choices[0].message.content)
```
If it is normal, please check your modification and configuration of this plugin.

**Comment by gonzalu** [comment] 2024-04-30 22:06
Thank you... I will try again on SHELL and then report my findings.

**Comment by gonzalu** [comment] 2024-05-01 15:41
Here is the result of your test script above:

```
E:\ComfyUI>python_embeded\python.exe test.py
Traceback (most recent call last):
  File "E:\ComfyUI\test.py", line 9, in <module>
    completion = client.chat.completions.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\openai\resources\chat\completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\openai\_base_client.py", line 1233, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\openai\_base_client.py", line 922, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\openai\_base_client.py", line 1013, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Missing Authentication header or invalid API key', 'code': 401}}
```

**Comment by gonzalu** [comment] 2024-05-01 15:55
and here is output from commandline using the test script from OpenRouter.ai

```
gonzalu@Astraea:~$ curl https://openrouter.ai/api/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENROUTER_API_KEY" \
  -d '{
  "model": "openai/gpt-3.5-turbo",
  "messages": [
    {"role": "user", "content": "What is the meaning of life?"}
  ]
}'











{"id":"gen-ouAzvdJmZZkzBFoOe5VGCNHQEuFR","model":"openai/gpt-3.5-turbo","object":"chat.completion","created":1714578867,"choices":[{"index":0,"message":{"role":"assistant","content":"The meaning of life is a deeply philosophical question that has been debated and pondered by humans for centuries. It ultimately depends on an individual's beliefs, values, and worldview. Some may find meaning in spiritual or religious beliefs, others may find meaning in personal relationships, experiences, or accomplishments. Ultimately, the meaning of life may be subjective and can vary for each person."},"finish_reason":"stop"}],"usage":{"prompt_tokens":14,"completion_tokens":74,"total_tokens":88,"total_cost":0.000118}}gonzalu@Astraea:~$
gonzalu@Astraea:~$
```

I will keep playing with it.

**Comment by gonzalu** [comment] 2024-05-01 16:02
OK is working again... 

![image](https://github.com/longgui0318/comfyui-llm-assistant/assets/32348862/9a7d90af-d35f-49b5-9127-5ce3c8f81a6f)


I have no idea what I did :) 

Thank you anyway.

**Comment by longgui0318** [comment] 2024-05-01 16:03
How are you passing the api_key, is it through env and if so is the key OPENROUTER_API_KEY.

**Comment by gonzalu** [comment] 2024-05-01 16:11
I have it in the config file. "config.yaml"

**Comment by longgui0318** [comment] 2024-05-01 16:14
Well, there's not enough information for me to guess the problem, so you can continue to contact me to troubleshoot if it comes up again

**Comment by gonzalu** [comment] 2024-05-01 16:21
No worries... I am sure it was user error LOL ... 

I decided to completely delete the custom node and then reinstall it from github and enter the API key into the config.yaml file again. 

Sorry to bother... I love the node... it works so good! 

Thank you. 

P.S. What's best model for Stable Diffusion prompts?

**Comment by longgui0318** [comment] 2024-05-01 18:01
It's hard to say which is the best, as there are different qualities for different image subjects, usually I would go for the mixtral-8x22b, which is very good value for money. Be careful to try different system prompts, some standard outputs such as those with "Output:" can be used to extract the main content by using regularization.

**Comment by gonzalu** [comment] 2024-05-01 20:39
Thank you so much... I appreciate you and your work!!

**Comment by gonzalu** [comment] 2024-05-04 01:29
I am sorry if this is a double post. I thought I hit COMMENT but I see it missing now :( 

I found the problem. 

The config.yaml file is overwritten when I do a ComfyUI Update All... 

That is why the error kept happening. My API key is overwritten by the node install process, I think. 

Thank you.

**Comment by longgui0318** [comment] 2024-05-06 01:37
I changed the name of the configuration template, this is to make it easier to change the configuration so it doesn't get overwritten due to pulls.

Please update and adjust the config.yaml

**Comment by gonzalu** [comment] 2024-05-06 02:54
Thank you. 

my workaround was to temporarily make the file read only in the OS. 

Thank you and I will test and reply back with findings. 

Cheers!

**Comment by gonzalu** [comment] 2024-05-06 05:56
OK, I did an update, and it is still working/config file unchanged. 

Thank you for your help

**Comment by longgui0318** [comment] 2024-05-06 07:32
ok. i close this

**Closed as completed by longgui0318** 2024-05-06 07:32 UTC
